FROM node:18-alpine
WORKDIR /app

# install dependencies (use npm ci if you have package-lock.json)
COPY package*.json ./
RUN npm install --production

COPY . .
ENV PORT=3000
EXPOSE 3000
CMD ["node", "server.js"]
